import type {ThemeDefinition} from "./theme-registry";

export const CORE_THEME: ThemeDefinition = {
  id: "core",
  label: "CYPHERV2.Themes.Core",
  sourceId: "cypherv2.core",
  properties: {
    "--cypherv2-surface-primary": "#1b1c1f",
    "--cypherv2-surface-secondary": "#25262a",
    "--cypherv2-surface-raised": "#303136",
    "--cypherv2-text-primary": "#f3f4f6",
    "--cypherv2-text-muted": "#a9acb2",
    "--cypherv2-accent": "#96082a",
    "--cypherv2-accent-hover": "#bd123f",
    "--cypherv2-border": "#484a50",
    "--cypherv2-danger": "#d85b66",
    "--cypherv2-success": "#5fa878",
    "--cypherv2-wound-pip-character": "var(--cypherv2-danger)",
    "--cypherv2-wound-pip-shield": "#8fc7ea",
    "--cypherv2-rank-expert": "#c4a7e7",
    "--cypherv2-rank-specialized": "#8fc7ea",
    "--cypherv2-rank-trained": "#85c99a",
    "--cypherv2-rank-untrained": "#a9acb2",
    "--cypherv2-rank-inability": "var(--cypherv2-danger)",
    "--cypherv2-cypher-power-low": "#a9acb2",
    "--cypherv2-cypher-power-medium": "#85c99a",
    "--cypherv2-cypher-power-advanced": "#8fc7ea",
    "--cypherv2-cypher-power-high": "#c4a7e7",
    "--cypherv2-cypher-power-ultra": "#e4a46d",
    "--cypherv2-pool-gauge-low": "#8f4d55",
    "--cypherv2-pool-gauge-high": "#567961",
    "--cypherv2-color-bg": "var(--cypherv2-surface-primary)",
    "--cypherv2-color-surface": "var(--cypherv2-surface-secondary)",
    "--cypherv2-color-surface-raised": "var(--cypherv2-surface-raised)",
    "--cypherv2-color-border": "var(--cypherv2-border)",
    "--cypherv2-color-text": "var(--cypherv2-text-primary)",
    "--cypherv2-color-muted": "var(--cypherv2-text-muted)",
    "--cypherv2-color-accent": "var(--cypherv2-accent)",
    "--cypherv2-color-warning": "#c78a51",
    "--cypherv2-color-danger": "var(--cypherv2-danger)",
    "--cypherv2-font-heading": "var(--font-primary, sans-serif)",
    "--cypherv2-radius": "0.5rem",
    "--cypherv2-shadow": "0 0.35rem 1rem rgb(0 0 0 / 30%)",
    "--cypherv2-space": "0.65rem",
    "--cypherv2-space-page": "0.85rem",
    "--cypherv2-space-compact": "0.35rem",
    "--cypherv2-space-tight": "0.2rem",
    "--cypherv2-scrollbar-size": "0.45rem",
    "--cypherv2-scrollbar-thumb": "var(--cypherv2-color-border)",
    "--cypherv2-scrollbar-track": "color-mix(in srgb, var(--cypherv2-color-bg) 70%, transparent)"
  }
};
